export const estudiantes = [
    { nombre: "Juan Pérez", edad: 20, notas: [8, 9, 7], activo: true, matricula: "A001", semestre: 3 },
    { nombre: "María López", edad: 22, notas: [9, 10, 8], activo: true, matricula: "A002", semestre: 5 },
    { nombre: "Carlos Sánchez", edad: 19, notas: [7, 6, 8], activo: false, matricula: "A003", semestre: 2 },
    { nombre: "Ana Martínez", edad: 21, notas: [10, 9, 9], activo: true, matricula: "A004", semestre: 4 },
    { nombre: "Luis Gómez", edad: 23, notas: [6, 7, 5], activo: true, matricula: "A005", semestre: 6 },
    { nombre: "Sofía Fernández", edad: 18, notas: [10, 10, 9], activo: true, matricula: "A006", semestre: 1 },
    { nombre: "Miguel Torres", edad: 21, notas: [8, 7, 6], activo: false, matricula: "A007", semestre: 3 },
    { nombre: "Laura Rivas", edad: 22, notas: [9, 8, 10], activo: true, matricula: "A008", semestre: 5 },
    { nombre: "Ricardo Castillo", edad: 20, notas: [7, 6, 7], activo: true, matricula: "A009", semestre: 2 },
    { nombre: "Valeria Morales", edad: 19, notas: [9, 9, 8], activo: false, matricula: "A010", semestre: 1 },
    { nombre: "Diego Aguilar", edad: 22, notas: [8, 8, 7], activo: true, matricula: "A011", semestre: 4 },
    { nombre: "Elena Mendoza", edad: 20, notas: [10, 9, 10], activo: true, matricula: "A012", semestre: 3 },
    { nombre: "Pablo Núñez", edad: 19, notas: [7, 5, 6], activo: false, matricula: "A013", semestre: 2 },
    { nombre: "Camila Vargas", edad: 21, notas: [9, 10, 10], activo: true, matricula: "A014", semestre: 4 },
    { nombre: "Álvaro Luna", edad: 23, notas: [6, 5, 7], activo: true, matricula: "A015", semestre: 6 },
    { nombre: "Isabel Reyes", edad: 18, notas: [10, 9, 9], activo: true, matricula: "A016", semestre: 1 },
    { nombre: "José Ortega", edad: 20, notas: [8, 7, 6], activo: false, matricula: "A017", semestre: 3 },
    { nombre: "Natalia Vega", edad: 22, notas: [9, 8, 7], activo: true, matricula: "A018", semestre: 5 },
    { nombre: "Rodrigo Peña", edad: 19, notas: [7, 6, 8], activo: false, matricula: "A019", semestre: 2 },
    { nombre: "Fernanda Ruiz", edad: 21, notas: [10, 10, 10], activo: true, matricula: "A020", semestre: 4 }
  ];

  export const estudiantes2 = [
    { nombre: "Juan Pérez", edad: 20, notas: [8, 9, 7], activo: true, precio: 200, semestre: 3 },
    { nombre: "María López", edad: 22, notas: [9, 10, 8], activo: true, precio: 250, semestre: 5 },
    { nombre: "Carlos Sánchez", edad: 19, notas: [7, 6, 8], activo: false, precio: 180, semestre: 2 },
    { nombre: "Ana Martínez", edad: 21, notas: [10, 9, 9], activo: true, precio: 220, semestre: 4 },
    { nombre: "Luis Gómez", edad: 23, notas: [6, 7, 5], activo: true, precio: 300, semestre: 6 },
    { nombre: "Sofía Fernández", edad: 18, notas: [10, 10, 9], activo: true, precio: 150, semestre: 1 },
    { nombre: "Miguel Torres", edad: 21, notas: [8, 7, 6], activo: false, precio: 200, semestre: 3 },
    { nombre: "Laura Rivas", edad: 22, notas: [9, 8, 10], activo: true, precio: 250, semestre: 5 },
    { nombre: "Ricardo Castillo", edad: 20, notas: [7, 6, 7], activo: true, precio: 180, semestre: 2 },
    { nombre: "Valeria Morales", edad: 19, notas: [9, 9, 8], activo: false, precio: 150, semestre: 1 },
    { nombre: "Diego Aguilar", edad: 22, notas: [8, 8, 7], activo: true, precio: 220, semestre: 4 },
    { nombre: "Elena Mendoza", edad: 20, notas: [10, 9, 10], activo: true, precio: 200, semestre: 3 },
    { nombre: "Pablo Núñez", edad: 19, notas: [7, 5, 6], activo: false, precio: 180, semestre: 2 },
    { nombre: "Camila Vargas", edad: 21, notas: [9, 10, 10], activo: true, precio: 220, semestre: 4 },
    { nombre: "Álvaro Luna", edad: 23, notas: [6, 5, 7], activo: true, precio: 300, semestre: 6 },
    { nombre: "Isabel Reyes", edad: 18, notas: [10, 9, 9], activo: true, precio: 150, semestre: 1 },
    { nombre: "José Ortega", edad: 20, notas: [8, 7, 6], activo: false, precio: 200, semestre: 3 },
    { nombre: "Natalia Vega", edad: 22, notas: [9, 8, 7], activo: true, precio: 250, semestre: 5 },
    { nombre: "Rodrigo Peña", edad: 19, notas: [7, 6, 8], activo: false, precio: 180, semestre: 2 },
    { nombre: "Fernanda Ruiz", edad: 21, notas: [10, 10, 10], activo: true, precio: 220, semestre: 4 }
];
